<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { fetchMovements, fetchPurchaseOrders, receivePurchase, type Movement, type PurchaseOrder } from '../../api/client'
const purchases = ref<PurchaseOrder[]>([]); const movements = ref<Movement[]>([]); const loading = ref(true); const acting = ref('')
async function load() { loading.value = true; try { [purchases.value, movements.value] = await Promise.all([fetchPurchaseOrders(), fetchMovements()]) } finally { loading.value = false } }
async function receive(id: string) { acting.value = id; try { const updated = await receivePurchase(id); purchases.value = purchases.value.map((item) => item.id === id ? updated : item) } finally { acting.value = '' } }
onMounted(load)
</script>
<template>
  <view class="page safe-top workbench"><view class="heading"><text class="eyebrow">WAREHOUSE DESK</text><text class="title">仓库工作台</text><text class="lead">把入库、出库和库存流水放在一个清晰的工作面</text></view><view class="tabs card"><text class="active">待入库 {{ purchases.filter((item) => item.status === '待入库').length }}</text><text>最近流水</text></view><view v-if="loading" class="state card"><text class="state-icon">◌</text>正在同步单据…</view><template v-else><view class="section-head"><text class="section-title">采购入库</text><text class="section-more">按时间排序</text></view><view class="order-list"><view v-for="order in purchases" :key="order.id" class="order card"><view class="order-top"><view><text class="order-name">{{ order.supplier }}</text><text class="order-id">{{ order.id }} · {{ order.warehouse }}</text></view><text class="status" :class="order.status === '待入库' ? 'warning' : 'success'">{{ order.status }}</text></view><view class="order-line"><text>采购 {{ order.items }} 个 SKU</text><text class="order-price">¥{{ order.amount.toLocaleString('zh-CN') }}</text></view><button v-if="order.status === '待入库'" class="primary-btn" :disabled="acting === order.id" @click="receive(order.id)">{{ acting === order.id ? '正在确认…' : '确认入库　→' }}</button></view></view><view class="section-head"><text class="section-title">最近库存流水</text><text class="section-more">全部流水 →</text></view><view class="movement-list"><view v-for="item in movements" :key="item.id" class="movement card"><view class="movement-icon" :class="item.type === '入库' ? 'in' : 'out'">{{ item.type === '入库' ? '↓' : '↑' }}</view><view class="movement-info"><text class="movement-name">{{ item.product }}</text><text class="small muted">{{ item.warehouse }} · {{ item.source }}</text></view><text class="movement-count" :class="item.type === '入库' ? 'in' : 'out'">{{ item.type === '入库' ? '+' : '-' }}{{ item.quantity }}</text></view></view></template></view>
</template>
<style scoped lang="scss">
.heading { margin-bottom:28rpx; }.lead { display:block; margin-top:18rpx; color:var(--muted); font-size:26rpx; line-height:1.5; }.tabs { display:flex; padding:8rpx; margin-bottom:26rpx; }.tabs text { flex:1; padding:19rpx; text-align:center; color:var(--muted); border-radius:18rpx; font-size:25rpx; }.tabs text.active { color:var(--brand); background:var(--brand-soft); font-weight:800; }.order-list,.movement-list { display:flex; flex-direction:column; gap:16rpx; }.order { padding:22rpx; }.order-top,.order-line { display:flex; justify-content:space-between; align-items:center; }.order-name { display:block; font-size:29rpx; font-weight:800; }.order-id { display:block; margin-top:6rpx; color:var(--muted); font-size:21rpx; }.status { padding:8rpx 14rpx; border-radius:99rpx; font-size:21rpx; font-weight:800; }.status.warning { background:#FFF6D8; color:#A77900; }.status.success { background:var(--success-soft); color:var(--success); }.order-line { margin:22rpx 0; color:var(--muted); font-size:24rpx; }.order-price { color:var(--ink); font-size:28rpx; font-weight:800; }.primary-btn { background:var(--action); color:#fff; border-radius:16rpx; font-size:26rpx; font-weight:800; height:78rpx; line-height:78rpx; }.movement { display:flex; align-items:center; padding:18rpx; }.movement-icon { width:62rpx; height:62rpx; border-radius:18rpx; display:flex; align-items:center; justify-content:center; font-size:34rpx; margin-right:16rpx; }.movement-icon.in { color:var(--success); background:var(--success-soft); }.movement-icon.out { color:var(--action); background:#FFF2E9; }.movement-info { flex:1; }.movement-name { display:block; font-size:27rpx; font-weight:800; }.movement-count { font-size:32rpx; font-weight:800; }.movement-count.in { color:var(--success); }.movement-count.out { color:var(--action); }
</style>
