<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { fetchSalesOrders, shipSale, type SalesOrder } from '../../api/client'
const orders = ref<SalesOrder[]>([]); const loading = ref(true); const acting = ref('')
async function load() { loading.value = true; try { orders.value = await fetchSalesOrders() } finally { loading.value = false } }
async function ship(id: string) { acting.value = id; try { const updated = await shipSale(id); orders.value = orders.value.map((item) => item.id === id ? updated : item) } finally { acting.value = '' } }
onMounted(load)
</script>
<template><view class="page safe-top orders"><view class="heading"><text class="eyebrow">OUTBOUND CENTER</text><text class="title">销售出库</text><text class="lead">从接单到发货，状态一眼可见</text></view><view v-if="loading" class="state card"><text class="state-icon">◌</text>正在加载销售单…</view><view v-else class="order-list"><view v-for="order in orders" :key="order.id" class="order card"><view class="order-top"><view><text class="order-name">{{ order.customer }}</text><text class="order-id">{{ order.id }} · {{ order.warehouse }}</text></view><text class="status" :class="order.status === '待发货' ? 'warning' : 'success'">{{ order.status }}</text></view><view class="order-line"><text>{{ order.items }} 个 SKU</text><text class="order-price">¥{{ order.amount.toLocaleString('zh-CN') }}</text></view><button v-if="order.status === '待发货'" class="primary-btn" :disabled="acting === order.id" @click="ship(order.id)">{{ acting === order.id ? '正在出库…' : '确认出库　→' }}</button><view v-else class="complete">✓ 已完成出库</view></view></view></view></template>
<style scoped lang="scss">
.heading { margin-bottom:32rpx; }.lead { display:block; margin-top:18rpx; color:var(--muted); font-size:26rpx; }.order-list { display:flex; flex-direction:column; gap:18rpx; }.order { padding:22rpx; }.order-top,.order-line { display:flex; justify-content:space-between; align-items:center; }.order-name { display:block; font-size:29rpx; font-weight:800; }.order-id { display:block; margin-top:6rpx; color:var(--muted); font-size:21rpx; }.status { padding:8rpx 14rpx; border-radius:99rpx; font-size:21rpx; font-weight:800; }.status.warning { background:#FFF6D8; color:#A77900; }.status.success { background:var(--success-soft); color:var(--success); }.order-line { margin:24rpx 0; color:var(--muted); font-size:24rpx; }.order-price { color:var(--ink); font-size:30rpx; font-weight:800; }.primary-btn { background:var(--action); color:#fff; border-radius:16rpx; font-size:26rpx; font-weight:800; height:78rpx; line-height:78rpx; }.complete { padding:20rpx; border-radius:16rpx; color:var(--success); background:var(--success-soft); text-align:center; font-size:25rpx; font-weight:700; }
</style>
